Repository DP2-E4-01/D03-Acme-Toolkit, pull requests merged in 2022-04, with the labels that each got.

#25 Temp/17 admin config
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationListService.java
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationShowService.java
  src/main/webapp/WEB-INF/views/administrator/configuration/form.jsp
  src/main/webapp/WEB-INF/views/administrator/configuration/list.jsp
  src/main/webapp/WEB-INF/views/administrator/configuration/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/configuration/messages-es.i18n
Labels: bug

#26 Feature/8 authenticated config
  .classpath
  src/main/java/acme/entities/configuration/Configuration.java
  src/main/java/acme/entities/item/Item.java
  src/main/java/acme/entities/item/ItemType.java
  src/main/java/acme/entities/patronage/Patronage.java
  src/main/java/acme/entities/patronagereport/PatronageReport.java
  src/main/java/acme/entities/quantity/Quantity.java
  src/main/java/acme/entities/tool/Tool.java
  src/main/java/acme/entities/toolkit/Toolkit.java
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationController.java
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationListService.java
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationRepository.java
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationShowService.java
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationUpdateService.java
  src/main/java/acme/features/authenticated/configuration/AuthenticatedConfigurationController.java
  src/main/java/acme/features/authenticated/configuration/AuthenticatedConfigurationRepository.java
  src/main/java/acme/features/authenticated/configuration/AuthenticatedConfigurationShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/component.csv
  src/main/webapp/WEB-INF/resources/sample-data/configuration.csv
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/resources/sample-data/patronageReport.csv
  src/main/webapp/WEB-INF/resources/sample-data/quantity.csv
  src/main/webapp/WEB-INF/resources/sample-data/tool.csv
  src/main/webapp/WEB-INF/resources/sample-data/toolkit.csv
  src/main/webapp/WEB-INF/views/administrator/configuration/form.jsp
  src/main/webapp/WEB-INF/views/administrator/configuration/list.jsp
  src/main/webapp/WEB-INF/views/administrator/configuration/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/configuration/messages-es.i18n
  src/main/webapp/WEB-INF/views/authenticated/configuration/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/configuration/messages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/configuration/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement

#27 issue #17 Feature/17 admin config
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationListService.java
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationShowService.java
  src/main/webapp/WEB-INF/views/administrator/configuration/form.jsp
  src/main/webapp/WEB-INF/views/administrator/configuration/list.jsp
  src/main/webapp/WEB-INF/views/administrator/configuration/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/configuration/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
Labels: enhancement

#29 Operations by inventors on patronages done
  src/main/java/acme/inventor/patronage/InventorPatronageController.java
  src/main/java/acme/inventor/patronage/InventorPatronageListService.java
  src/main/java/acme/inventor/patronage/InventorPatronageRepository.java
  src/main/java/acme/inventor/patronage/InventorPatronageShowService.java
  src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage/list.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage/messages-es.i18n
Labels: enhancement

#30 Feature/15 operations patronage reports
  src/main/java/acme/features/patron/patronage/PatronPatronageController.java
  src/main/java/acme/features/patron/patronage/PatronPatronageListService.java
  src/main/java/acme/features/patron/patronage/PatronPatronageRepository.java
  src/main/java/acme/features/patron/patronage/PatronPatronageShowService.java
  src/main/java/acme/features/patron/patronageReport/PatronPatronageReportController.java
  src/main/java/acme/features/patron/patronageReport/PatronPatronageReportListService.java
  src/main/java/acme/features/patron/patronageReport/PatronPatronageReportRepository.java
  src/main/java/acme/features/patron/patronageReport/PatronPatronageReportShowService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/patron/patronage-report/form.jsp
  src/main/webapp/WEB-INF/views/patron/patronage-report/list.jsp
  src/main/webapp/WEB-INF/views/patron/patronage-report/messages-en.i18n
  src/main/webapp/WEB-INF/views/patron/patronage-report/messages-es.i18n
  src/main/webapp/WEB-INF/views/patron/patronage/form.jsp
  src/main/webapp/WEB-INF/views/patron/patronage/list.jsp
  src/main/webapp/WEB-INF/views/patron/patronage/messages-en.i18n
  src/main/webapp/WEB-INF/views/patron/patronage/messages-es.i18n
Labels: enhancement

#32 Feature/14 operations patronages
  src/main/java/acme/features/patron/patronage/PatronPatronageShowService.java
  src/main/webapp/WEB-INF/views/patron/patronage/form.jsp
  src/main/webapp/WEB-INF/views/patron/patronage/messages-en.i18n
  src/main/webapp/WEB-INF/views/patron/patronage/messages-es.i18n
Labels: enhancement

#33 Feature/4 operations principals component
  src/main/java/acme/featuras/any/item/AnyComponentController.java
  src/main/java/acme/featuras/any/item/AnyComponentListService.java
  src/main/java/acme/featuras/any/item/AnyComponentRepository.java
  src/main/java/acme/featuras/any/item/AnyComponentShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/views/any/item/form.jsp
  src/main/webapp/WEB-INF/views/any/item/list.jsp
  src/main/webapp/WEB-INF/views/any/item/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/item/messages-es.i18n
Labels: enhancement

#34 Task007: done
  src/main/java/acme/features/authenticated/announcement/AuthenticatedAnnouncementController.java
  src/main/java/acme/features/authenticated/announcement/AuthenticatedAnnouncementListService.java
  src/main/java/acme/features/authenticated/announcement/AuthenticatedAnnouncementRepository.java
  src/main/java/acme/features/authenticated/announcement/AuthenticatedAnnouncementShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/announcement.csv
  src/main/webapp/WEB-INF/views/authenticated/announcement/form.jsp
  src/main/webapp/WEB-INF/views/authenticated/announcement/list.jsp
  src/main/webapp/WEB-INF/views/authenticated/announcement/messages-en.i18n
  src/main/webapp/WEB-INF/views/authenticated/announcement/messages-es.i18n
Labels: enhancement

#35 Feature/18 admin dashboard issue #18
  src/main/java/acme/features/administrator/configurations/AdministratorConfigurationController.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardController.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardRepository.java
  src/main/java/acme/features/administrator/dashboard/AdministratorDashboardShowService.java
  src/main/java/acme/forms/AdministratorDashboard.java
  src/main/java/acme/forms/Dashboard.java
  src/main/java/acme/forms/PatronDashboard.java
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/resources/sample-data/patronage.csv
  src/main/webapp/WEB-INF/views/administrator/dashboard/form.jsp
  src/main/webapp/WEB-INF/views/administrator/dashboard/list.jsp
  src/main/webapp/WEB-INF/views/administrator/dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/administrator/dashboard/messages-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement

#36 Feature/6 operations principals toolkit
  src/main/java/acme/entities/toolkit/Status.java
  src/main/java/acme/entities/toolkit/Toolkit.java
  src/main/java/acme/features/any/item/AnyComponentController.java
  src/main/java/acme/features/any/item/AnyComponentListService.java
  src/main/java/acme/features/any/item/AnyComponentRepository.java
  src/main/java/acme/features/any/item/AnyComponentShowService.java
  src/main/java/acme/features/any/item/AnyItemListByToolkit.java
  src/main/java/acme/features/any/toolkits/AnyToolkitController.java
  src/main/java/acme/features/any/toolkits/AnyToolkitListService.java
  src/main/java/acme/features/any/toolkits/AnyToolkitRepository.java
  src/main/java/acme/features/any/toolkits/AnyToolkitShowService.java
  src/main/webapp/WEB-INF/resources/sample-data/toolkit.csv
  src/main/webapp/WEB-INF/views/any/toolkit/form.jsp
  src/main/webapp/WEB-INF/views/any/toolkit/list.jsp
  src/main/webapp/WEB-INF/views/any/toolkit/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/toolkit/messages-es.i18n
Labels: enhancement

#39 Operations by all principals on user accounts done
  src/main/java/acme/features/any/userAccount/AnyUserAccountController.java
  src/main/java/acme/features/any/userAccount/AnyUserAccountListEnabledService.java
  src/main/java/acme/features/any/userAccount/AnyUserAccountRepository.java
  src/main/java/acme/features/any/userAccount/AnyUserAccountShowService.java
  src/main/webapp/WEB-INF/views/any/user-account/form.jsp
  src/main/webapp/WEB-INF/views/any/user-account/list.jsp
  src/main/webapp/WEB-INF/views/any/user-account/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/user-account/messages-es-i18n
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
Labels: enhancement

#40 Task-016:formated html
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/form.jsp
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-en.i18n
  src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-es.i18n
Labels: enhancement

#41 Test/8 authenticated configuration
  src/test/java/acme/testing/authenticated/configuration/AuthenticatedConfigurationShowTest.java
  src/test/resources/authenticated/configuration/show.csv
Labels: enhancement

#44 Test task006 done
  src/main/java/acme/features/any/toolkits/AnyToolkitListService.java
  src/main/java/acme/features/any/toolkits/AnyToolkitShowService.java
  src/main/webapp/WEB-INF/views/any/toolkit/list.jsp
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/test/java/acme/testing/any/toolkit/AnyToolkitTest.java
  src/test/resources/any/toolkit/toolkit.csv
Labels: enhancement

#43 Test/11 inventor toolkit
  src/test/java/acme/testing/authenticated/configuration/AuthenticatedConfigurationShowTest.java
  src/test/java/acme/testing/inventor/toolkit/InventorToolkitListOwnTest.java
  src/test/resources/inventor/toolkit/list-own.csv
Labels: enhancement

#45 Task003 Done
  .classpath
  src/main/java/acme/features/any/chirp/AnyChirpController.java
  src/main/java/acme/features/any/chirp/AnyChirpListService.java
  src/main/java/acme/features/any/chirp/AnyChirpRepository.java
  src/main/webapp/WEB-INF/resources/sample-data/chirp.csv
  src/main/webapp/WEB-INF/views/any/chirp/list.jsp
  src/main/webapp/WEB-INF/views/any/chirp/messages-en.i18n
  src/main/webapp/WEB-INF/views/any/chirp/messages-es.i18n
Labels: enhancement

#46 Test/3 operations principals chirps
  logs/performance-requests.csv
  logs/performance-requests;2022-04-24T21.44.43.189.csv
  logs/performance-requests;2022-04-24T21.45.38.029.csv
  logs/performance-requests;2022-04-24T21.47.26.671.csv
  logs/performance-tests.csv
  logs/performance-tests;2022-04-24T21.44.43.187.csv
  logs/performance-tests;2022-04-24T21.45.38.027.csv
  logs/performance-tests;2022-04-24T21.47.26.669.csv
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/test/java/acme/testing/any/chirp/TestsAnyChirp.java
  src/test/resources/any/chirp/chirp.csv
Labels: enhancement

#49 Test Task007 done
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/test/java/acme/testing/authenticated/announcement/AuthenticatedAnnouncementTest.java
  src/test/resources/authenticated/announcement/announcement.csv
Labels: enhancement

#48 Feature/13 inventor patronage reports
  src/main/java/acme/features/inventor/patronage/InventorPatronageListService.java
  src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportController.java
  src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportListByPatronageService.java
  src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportRepository.java
  src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportShowService.java
  src/main/webapp/WEB-INF/views/inventor/patronage-report/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/list.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-es.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp
  src/main/webapp/WEB-INF/views/inventor/patronage/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/patronage/messages-es.i18n
Labels: enhancement

#51 Test Task013 Done
  logs/performance-requests;2022-04-25T16.03.30.622.csv
  logs/performance-requests;2022-04-25T16.28.55.751.csv
  logs/performance-requests;2022-04-25T16.31.01.289.csv
  logs/performance-requests;2022-04-25T16.32.38.147.csv
  logs/performance-requests;2022-04-25T16.34.56.166.csv
  logs/performance-requests;2022-04-25T16.38.45.203.csv
  logs/performance-requests;2022-04-25T16.43.06.602.csv
  logs/performance-requests;2022-04-25T16.44.23.479.csv
  logs/performance-requests;2022-04-25T16.57.40.903.csv
  logs/performance-requests;2022-04-25T17.01.46.328.csv
  logs/performance-requests;2022-04-25T17.13.57.513.csv
  logs/performance-requests;2022-04-25T17.18.22.676.csv
  logs/performance-requests;2022-04-25T17.20.45.461.csv
  logs/performance-requests;2022-04-25T17.22.07.905.csv
  logs/performance-requests;2022-04-25T17.25.49.426.csv
  logs/performance-requests;2022-04-25T17.28.03.169.csv
  logs/performance-requests;2022-04-25T17.30.56.672.csv
  logs/performance-requests;2022-04-25T17.32.12.713.csv
  logs/performance-tests.csv
  logs/performance-tests;2022-04-25T16.03.30.62.csv
  logs/performance-tests;2022-04-25T16.28.55.748.csv
  logs/performance-tests;2022-04-25T16.31.01.279.csv
  logs/performance-tests;2022-04-25T16.32.38.141.csv
  logs/performance-tests;2022-04-25T16.34.56.161.csv
  logs/performance-tests;2022-04-25T16.38.45.199.csv
  logs/performance-tests;2022-04-25T16.43.06.598.csv
  logs/performance-tests;2022-04-25T16.44.23.477.csv
  logs/performance-tests;2022-04-25T16.57.40.901.csv
  logs/performance-tests;2022-04-25T17.01.46.326.csv
  logs/performance-tests;2022-04-25T17.13.57.508.csv
  logs/performance-tests;2022-04-25T17.18.22.674.csv
  logs/performance-tests;2022-04-25T17.20.45.459.csv
  logs/performance-tests;2022-04-25T17.22.07.9.csv
  logs/performance-tests;2022-04-25T17.25.49.423.csv
  logs/performance-tests;2022-04-25T17.28.03.165.csv
  logs/performance-tests;2022-04-25T17.30.56.668.csv
  logs/performance-tests;2022-04-25T17.32.12.709.csv
  src/main/webapp/WEB-INF/resources/sample-data/patronage.csv
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/test/java/acme/testing/inventor/patronageReport/TestInventorPatronageReport.java
  src/test/resources/inventor/patronageReport/patronage.csv
Labels: enhancement

#52 Test Operations by all principals on user accounts done
  src/main/webapp/WEB-INF/resources/sample-data/patronage.csv
  src/test/java/acme/testing/any/userAccount/AnyUserAccountListTest.java
  src/test/resources/any/userAccount/list-enabled.csv
Labels: Test Case

#53 Task-014:Tests Done
  src/test/java/acme/testing/patron/patronage/PatronPatronageTest.java
  src/test/resources/patron/patronage/patronage.csv
Labels: Test Case

#54 issue #17 tests
  src/main/webapp/WEB-INF/resources/sample-data/configuration.csv
  src/test/java/acme/testing/administrator/configuration/AdministratorConfigurationShowTest.java
  src/test/resources/administrator/configuration/show.csv
Labels: Test Case

#55 Task-015:Test Done
  src/main/webapp/WEB-INF/resources/sample-data/patronageReport.csv
  src/test/java/acme/testing/patron/patronageReport/PatronPatronageReportTest.java
  src/test/resources/patron/patronage-report/patronage.csv
Labels: Test Case

#56 Test/16 patron dashboard
  src/main/webapp/WEB-INF/resources/sample-data/patronage.csv
  src/test/java/acme/testing/patron/dashboard/PatronDashboardTest.java
Labels: Test Case

#57 Task 009: Done (tests included)
  src/main/java/acme/features/inventor/item/InventorComponentListService.java
  src/main/java/acme/features/inventor/item/InventorComponentShowService.java
  src/main/java/acme/features/inventor/item/InventorItemController.java
  src/main/java/acme/features/inventor/item/InventorItemRepository.java
  src/main/webapp/WEB-INF/resources/sample-data/item.csv
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/main/webapp/WEB-INF/views/inventor/item/form.jsp
  src/main/webapp/WEB-INF/views/inventor/item/list.jsp
  src/main/webapp/WEB-INF/views/inventor/item/messages-en.i18n
  src/main/webapp/WEB-INF/views/inventor/item/messages-es.i18n
  src/test/java/acme/testing/inventor/item/ComponentListServiceTest.java
  src/test/resources/inventor/item/component.csv
Labels: enhancement, Test Case

#58 Test/5 operations tools
  src/main/java/acme/features/any/item/AnyComponentController.java
  src/main/java/acme/features/any/item/AnyToolListService.java
  src/main/webapp/WEB-INF/views/any/item/form.jsp
  src/test/java/acme/testing/any/items/AnyItemsTest.java
  src/test/resources/any/item/tools.csv
Labels: Test Case

#59 Test task004 done
  logs/performance-requests.csv
  logs/performance-tests.csv
  src/test/java/acme/testing/any/items/AnyItemsTest.java
  src/test/resources/any/item/components.csv
Labels: Test Case

#60 task 010: Done (test included)
  src/main/java/acme/features/inventor/item/InventorItemController.java
  src/main/java/acme/features/inventor/item/InventorItemListOwnComponentService.java
  src/main/java/acme/features/inventor/item/InventorItemListOwnToolService.java
  src/main/java/acme/features/inventor/item/InventorItemRepository.java
  src/main/java/acme/features/inventor/item/InventorItemShowService.java
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/test/java/acme/testing/inventor/item/ToolListServiceTest.java
  src/test/resources/inventor/item/tool.csv
Labels: enhancement, Test Case

#62 Hotfix
  src/main/java/acme/features/any/item/AnyItemController.java
  src/main/java/acme/features/any/item/AnyToolListService.java
  src/main/webapp/WEB-INF/views/any/item/list.jsp
  src/test/java/acme/testing/any/items/AnyItemsTest.java
  src/test/java/acme/testing/any/toolkit/AnyToolkitTest.java
Labels: bug

#63 Hotfix tests
  src/main/webapp/WEB-INF/views/fragments/menu-en.i18n
  src/main/webapp/WEB-INF/views/fragments/menu-es.i18n
  src/main/webapp/WEB-INF/views/fragments/menu.jsp
  src/test/java/acme/testing/administrator/dashboard/AdministratorDashboardTest.java
  src/test/java/acme/testing/any/toolkit/AnyToolkitTest.java
  src/test/java/acme/testing/inventor/item/ComponentListServiceTest.java
  src/test/java/acme/testing/inventor/item/ToolListServiceTest.java
  src/test/java/acme/testing/inventor/patronage/InventorPatronageListOwnTest.java
  src/test/java/acme/testing/inventor/toolkit/InventorToolkitListOwnTest.java
  src/test/resources/inventor/patronageReport/patronage.csv
Labels: bug

#65 quickfix
  .gitignore
  src/test/java/acme/testing/any/items/AnyItemsTest.java
Labels: bug

#66 Develop
  .gitignore
  src/test/java/acme/testing/any/items/AnyItemsTest.java
Labels: bug
